name: 'DB Dev Bot Action Webhook'
description: 'A Github workflow action to call a webhook with payload data from the event. Support for JSON or URL encoded endpoints.'
inputs:
  webhook_auth:
    description: 'Credentials to be used for BASIC authentication (optional)'
  data:
    description: 'Optional additional data to include in the payload'
    required: true
    
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'database'
  color: 'purple'
